# Contigious vs non-contigious tensor

It’s a flag indicating, if the memory is contiguously stored or not.

Let use an example to see, how we can get a non-contiguous tensor.

In [1]:
import torch
# Create a tensor of shape [4, 3]
x = torch.arange(12).view(4, 3)
print(x, x.stride())

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) (3, 1)


In [2]:
y = x.t()
print(y, y.stride())
print(y.is_contiguous())

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]) (1, 3)
False


In [3]:
try:
    y = y.view(-1)
except RuntimeError as e:
    print(e)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [4]:
y = y.contiguous()
print(y.stride())
y = y.view(-1)
print(y)

(4, 1)
tensor([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])
